name: CI Workflow  # Name of the workflow

on:
  push:
    branches:
      - main       # Trigger on push to main branch
  pull_request:
    branches:
      - main       # Trigger on PRs to main branch

jobs:
  build:
    runs-on: ubuntu-latest   # The virtual environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # Step to clone repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          retention-days: 1 # 90 is the default


      - name: Run tests
        run: npm test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
